### ISSUE TITLE
No results with multiple discs

### ISSUE THREAD

**Issue by kbuffington** [marc2k3/foo_musicbrainz#2]
First of all, it's awesome to have this component being updated again. I can finally get results from artists and albums with a `/` in the name without getting an XML error!

I did some testing using the Search by Artist/Album, and attempted to get data for a 2-disc album which contained 23 tracks total. It queried 6 results, and then only showed me one of them which was a DVD version which had all 23 tracks on 1 disc. I was able to replicate this behavior on other multi-disc releases, usually getting the "no results" message. It seems that when determining matches for multi-disc releases it doesn't take into account tracks being spread across discs and instead thinks they all belong to disc 1.

Another thing I noticed is that querying is slow. I searched for "AC/DC - Highway to Hell" which had 35 matches... and the query took 65 seconds to execute. I assume this is rate limiting related, but it's kind of painful now. I haven't checked the code out yet, but it might be possible to do the requests async with 1 second delay instead of waiting for a response, then waiting 1 sec (I'm just guessing that's what's happening).

**Comment by marc2k3** [comment]
Yup, it's never supported multi-disc lookups. You have to suffer by doing one disc at a time. :disappointed: 

All the data for multi disc sets is contained within a single release lookup but any discs that don't match the original selection count are filtered out. 

For example, this 2 disc album has an identical number of tracks for each disc and I have to choose which disc I want to apply to my selection.

![1](https://user-images.githubusercontent.com/34617027/64638472-c06bfd00-d3fd-11e9-9531-d03cdff138c8.png)

This is also a recognised multi-disc release (see tagger discs combo box) but it's only letting me pick the one disc with the number of tracks matching my selection.

![2](https://user-images.githubusercontent.com/34617027/64638474-c06bfd00-d3fd-11e9-9605-4a2b7e74e06c.png)

I may consider multi-disc support but it's only likely to happen if you supply the albumid. This issue will remain open while I think about it.

As for artist/album looks there is indeed an enforced delay between each lookup due to rate limiting. Their docs specify 1s but I'm already delaying for 1100ms +network latency +response parsing and I'm still getting occasional network errors. I think any effort to try hit them at exact 1s intervals isn't going to work.

Right now, the best thing to do with a huge number of releases is to find the exact release you want on the website and paste the URL into the Album ID context menu popup. This is mentioned in the readme.

```
You can now paste full release URLs like

https://musicbrainz.org/release/76a601d9-a1a6-4112-aad5-d63bc85db9b6

in to the MBID query dialog and it will automatically strip the URL so
you're left with just the MBID like "76a601d9-a1a6-4112-aad5-d63bc85db9b6".
This is useful if a given artist/album has many releases and you find it
easier to find the correct one on the musicbrainz.org website. This will
only work with "release" URLs and not "release-group" and the track count
must always match the selection.
```

Yes it's cumbersome but it's probably the most practical solution at the moment. Of course if they're CD rips, you might get results from TOC lookups.

One thing I can do is check the preliminary artist/album lookup response. Maybe it's feasible to present a summary and let you pick a release but I've never inspected the JSON to see how much info it contains.

**Comment by kbuffington** [comment]
The old version did work with multi-disc releases... it would just only show you a single disc at a time. I never bothered to inspect how that worked though. It would update tags on both discs when you clicked "Update files".

![image](https://user-images.githubusercontent.com/2282004/64642652-74589280-d3d4-11e9-85e1-a97de26e07af.png)

The old version didn't seem to have many issues with 503s, and would seem to make requests as fast as possible... but maybe that's because the XML version isn't hit as often?

I wrote my own external tagger which uses musicbrainz several years ago and the approach I settled on was querying by Artist/Album Title to get a list of all matching releases (ignoring tracknumbers/discs which you can't really do) and then querying the first entry, but afterwards only querying for the individual reid when the user clicks on one of the albums for closer inspection (why pull 35 requests if the first has what the user wants). Then I cached the results to prevent repeating requests.

I'll take a look at the repo in the next day or two here, and might be able to provide some assistance.

**Comment by marc2k3** [comment]
Oh right, I better get to work restoring multi-disc support as it was before. I honestly didn't think it worked.

**Comment by marc2k3** [comment]
I've made some progress on this - you can preview all tracks at once without using the combo box to switch discs. I just a need to create a better interface for editing disc subtitles.

![Untitled](https://user-images.githubusercontent.com/34617027/64672410-5423e480-d463-11e9-9b26-0b55fcdf3306.png)

**Comment by marc2k3** [comment]
A new beta is out for testing.

https://github.com/marc2k3/foo_musicbrainz/releases

**Comment by marc2k3** [comment]
I think it's fair to say this is fixed now. Closing.
