### ISSUE TITLE
A bit more control

### ISSUE THREAD

**Issue by Forage** [marc2k3/foo_musicbrainz#6]
Great to see this plugin getting some love again. Many thanks.

There are two things I always do manually when tagging with MB data.
1. Clear the "First release date" field to not have this value stored (prevent date displaying issues with some applications/devices)
2. Systematically store the artist as "Album artist" as well, even when it's not a VA release (prevents infamous "Greatest hits" mixing)

Would it be possible and make sense to you to add the options to have this done automatically?

**Comment by marc2k3** [comment]
1. Currently, it's not written if it matches the normal `DATE`. I guess I could consider adding an option to never write it.

2. There is already an option in the `Preferences` to always write `Album artist`. It's off by default so you'll need to go enable it.

**Comment by Forage** [comment]
Thanks for the addition, much appreciated.
Sorry about the redundant album artist request, I should have checked more carefully first instead of assuming.

**Comment by marc2k3** [comment]
You can grab the new download here: https://github.com/marc2k3/foo_musicbrainz/releases

**Comment by jesus2099** [comment]
Hello @Forage,

What application or device did have issues with ORIGINAL RELEASE DATE and what displaying issue did they have?
You could report it to them.

You know that you only have the re-edition release year now?
Wouldn't you prefer having 1972 for [ZIGGY STARDUST](https://musicbrainz.org/release/80e6d075-935f-32f0-a612-e5243af2e5f6) instead of 2007, for instance?

**Comment by Forage** [comment]
There are two issues with that date:
1. It has the full date instead of only the year, which causes display issues
2. I don't have enough control over which value is used/displayed if both are available

So I simply prefer to not store it at all. Only in cases where the value differs I do store it sometimes, but only the year. A more exact date is of  no value to me anyway.

**Comment by jesus2099** [comment]
Sounds like those issues could be fixed by the player.

Feature suggestions:

1. Fix the display bug or truncate to year
2. Have a setting to always display either earlier or later date

FWIW, because I think it's a pity to limit your data because of a player that could work better. Like when Unicode was not possible in Winamp, I had to move to foobar2000.

**Comment by Forage** [comment]
They could very well be yes, but unfortunately we do not live in a world in which all our wishes are being honoured, no matter how much you ask or how good the ideas are.

**Comment by jesus2099** [comment]
So you asked bug fix or feature over there? and they did not fix but you asked complexity here and it was added promptly. 😉

**Comment by marc2k3** [comment]
@jesus2099 , none of these things are an issue within foobar2000 itself. Perhaps you should familiarise yourself with the scripting features that are available such as $if/$if2/$year etc.

https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference

Of course none of that helps @Forage because I actually read what they wrote in the first post - maybe you could try it too...

>  (prevent date displaying issues with some applications/devices)

**Comment by jesus2099** [comment]
I read it and was [suggesting](https://github.com/marc2k3/foo_musicbrainz/issues/6#issuecomment-581915297) contacting said _application/device_ and asking them to manage their issues, if possible.

Is the default still to write original release date only when different, like album artist?

**Comment by Forage** [comment]
This additional discussion would only have had some benefit if the "Use year instead of full date" preference would be applied consistently for both `DATE` and `ORIGINAL RELEASE DATE` now ;)
Changing the string to "Use year instead of full date**s**" as a consequence.

**Comment by marc2k3** [comment]
I think ORIGINAL RELEASE DATE should always be written in full so I've updated the label in the `Preferences`.

![image](https://user-images.githubusercontent.com/34617027/73753516-bf47bd80-475a-11ea-8f6d-496f8e2c606d.png)

**Comment by Forage** [comment]
Why only this option for DATE? I don't see why people would only be interested in a year for DATE but would still have a need for a full date for ORIGINAL RELEASE DATE. This would only be valuable if you have ORIGINAL RELEASE DATE set to always be written.
An alternative would be to provide yet another preference, but please get rid of "Write ASIN" in that case ;)

**Comment by marc2k3** [comment]
Fuck it, I can't be bothered dealing with user feedback any more.
